



local_trends = [{'trends': 
                     [{'name': '#VMAs', 'url': 'http://twitter.com/search?q=%23VMAs', 'promoted_content': None, 'query': '%23VMAs', 'tweet_volume': 2343163}, 
                      {'name': 'Missy', 'url': 'http://twitter.com/search?q=Missy', 'promoted_content': None, 'query': 'Missy', 'tweet_volume': 198489}, 
                      {'name': 'i-10 west', 'url': 'http://twitter.com/search?q=%22i-10+west%22', 'promoted_content': None, 'query': '%22i-10+west%22', 'tweet_volume': None}, 
                      {'name': '#SU23', 'url': 'http://twitter.com/search?q=%23SU23', 'promoted_content': None, 'query': '%23SU23', 'tweet_volume': None}, 
                      {'name': 'Taylor Swift', 'url': 'http://twitter.com/search?q=%22Taylor+Swift%22', 'promoted_content': None, 'query': '%22Taylor+Swift%22', 'tweet_volume': 248693}, 
                      {'name': 'Bryce', 'url': 'http://twitter.com/search?q=Bryce', 'promoted_content': None, 'query': 'Bryce', 'tweet_volume': 23680}, 
                      {'name': 'Mane', 'url': 'http://twitter.com/search?q=Mane', 'promoted_content': None, 'query': 'Mane', 'tweet_volume': 56318}, 
                      {'name': 'Bret Stephens', 'url': 'http://twitter.com/search?q=%22Bret+Stephens%22', 'promoted_content': None, 'query': '%22Bret+Stephens%22', 'tweet_volume': 73761}, 
                      {'name': '#TuesdayThoughts', 'url': 'http://twitter.com/search?q=%23TuesdayThoughts', 'promoted_content': None, 'query': '%23TuesdayThoughts', 'tweet_volume': 76535}, 
                      {'name': '#HowIGotThroughHighSchool', 'url': 'http://twitter.com/search?q=%23HowIGotThroughHighSchool', 'promoted_content': None, 'query': '%23HowIGotThroughHighSchool', 'tweet_volume': None}, 
                      {'name': '#TopSeinfeldEP', 'url': 'http://twitter.com/search?q=%23TopSeinfeldEP', 'promoted_content': None, 'query': '%23TopSeinfeldEP', 'tweet_volume': None}, 
                      {'name': 'Doral', 'url': 'http://twitter.com/search?q=Doral', 'promoted_content': None, 'query': 'Doral', 'tweet_volume': 152508}, 
                      {'name': 'Cassie', 'url': 'http://twitter.com/search?q=Cassie', 'promoted_content': None, 'query': 'Cassie', 'tweet_volume': 23707}, 
                      {'name': 'Gronk', 'url': 'http://twitter.com/search?q=Gronk', 'promoted_content': None, 'query': 'Gronk', 'tweet_volume': None}, 
                      {'name': 'Robert Pattinson', 'url': 'http://twitter.com/search?q=%22Robert+Pattinson%22', 'promoted_content': None, 'query': '%22Robert+Pattinson%22', 'tweet_volume': None}, 
                      {'name': 'Neal Casal', 'url': 'http://twitter.com/search?q=%22Neal+Casal%22', 'promoted_content': None, 'query': '%22Neal+Casal%22', 'tweet_volume': None}, 
                      {'name': 'Roxane', 'url': 'http://twitter.com/search?q=Roxane', 'promoted_content': None, 'query': 'Roxane', 'tweet_volume': None}, 
                      {'name': 'Alex Fine', 'url': 'http://twitter.com/search?q=%22Alex+Fine%22', 'promoted_content': None, 'query': '%22Alex+Fine%22', 'tweet_volume': None}, 
                      {'name': 'Jeremy Lin', 'url': 'http://twitter.com/search?q=%22Jeremy+Lin%22', 'promoted_content': None, 'query': '%22Jeremy+Lin%22', 'tweet_volume': None}, 
                      {'name': 'Mark Martin', 'url': 'http://twitter.com/search?q=%22Mark+Martin%22', 'promoted_content': None, 'query': '%22Mark+Martin%22', 'tweet_volume': None}, 
                      {'name': 'Tsitsipas', 'url': 'http://twitter.com/search?q=Tsitsipas', 'promoted_content': None, 'query': 'Tsitsipas', 'tweet_volume': None}, 
                      {'name': 'Days of Thunder', 'url': 'http://twitter.com/search?q=%22Days+of+Thunder%22', 'promoted_content': None, 'query': '%22Days+of+Thunder%22', 'tweet_volume': None}, 
                      {'name': '92 Billion', 'url': 'http://twitter.com/search?q=%2292+Billion%22', 'promoted_content': None, 'query': '%2292+Billion%22', 'tweet_volume': None}, 
                      {'name': 'Jeff Hafley', 'url': 'http://twitter.com/search?q=%22Jeff+Hafley%22', 'promoted_content': None, 'query': '%22Jeff+Hafley%22', 'tweet_volume': None}, 
                      {'name': 'fish smithson', 'url': 'http://twitter.com/search?q=%22fish+smithson%22', 'promoted_content': None, 'query': '%22fish+smithson%22', 'tweet_volume': None}, 
                      {'name': '#KeurigRoutine', 'url': 'http://twitter.com/search?q=%23KeurigRoutine', 'promoted_content': None, 'query': '%23KeurigRoutine', 'tweet_volume': None}, 
                      {'name': '#IThoughtThatLoveWas', 'url': 'http://twitter.com/search?q=%23IThoughtThatLoveWas', 'promoted_content': None, 'query': '%23IThoughtThatLoveWas', 'tweet_volume': None}, 
                      {'name': '#HurricaneDorian', 'url': 'http://twitter.com/search?q=%23HurricaneDorian', 'promoted_content': None, 'query': '%23HurricaneDorian', 'tweet_volume': None}, 
                      {'name': '#TipTuesday', 'url': 'http://twitter.com/search?q=%23TipTuesday', 'promoted_content': None, 'query': '%23TipTuesday', 'tweet_volume': None}, 
                      {'name': '#QUANTUMLEAP', 'url': 'http://twitter.com/search?q=%23QUANTUMLEAP', 'promoted_content': None, 'query': '%23QUANTUMLEAP', 'tweet_volume': 454616}, 
                      {'name': '#DefendCivilRights', 'url': 'http://twitter.com/search?q=%23DefendCivilRights', 'promoted_content': None, 'query': '%23DefendCivilRights', 'tweet_volume': None}, 
                      {'name': '#tmobiletuesdays', 'url': 'http://twitter.com/search?q=%23tmobiletuesdays', 'promoted_content': None, 'query': '%23tmobiletuesdays', 'tweet_volume': 16931}, 
                      {'name': '#MeekFree', 'url': 'http://twitter.com/search?q=%23MeekFree', 'promoted_content': None, 'query': '%23MeekFree', 'tweet_volume': None}, 
                      {'name': '#IAmOnStrikeUntil', 'url': 'http://twitter.com/search?q=%23IAmOnStrikeUntil', 'promoted_content': None, 'query': '%23IAmOnStrikeUntil', 'tweet_volume': None}, 
                      {'name': '#callyourshot', 'url': 'http://twitter.com/search?q=%23callyourshot', 'promoted_content': None, 'query': '%23callyourshot', 'tweet_volume': None}, 
                      {'name': '#CiscoIMPACT', 'url': 'http://twitter.com/search?q=%23CiscoIMPACT', 'promoted_content': None, 'query': '%23CiscoIMPACT', 'tweet_volume': None}, 
                      {'name': '#PSLIVE19', 'url': 'http://twitter.com/search?q=%23PSLIVE19', 'promoted_content': None, 'query': '%23PSLIVE19', 'tweet_volume': None}, 
                      {'name': '#TheKing', 'url': 'http://twitter.com/search?q=%23TheKing', 'promoted_content': None, 'query': '%23TheKing', 'tweet_volume': None}, 
                      {'name': '#OAOATaehyun', 'url': 'http://twitter.com/search?q=%23OAOATaehyun', 'promoted_content': None, 'query': '%23OAOATaehyun', 'tweet_volume': 35136}, 
                      {'name': '#NCTOH2019', 'url': 'http://twitter.com/search?q=%23NCTOH2019', 'promoted_content': None, 'query': '%23NCTOH2019', 'tweet_volume': None}, 
                      {'name': '#TheWorstMarriagesInclude', 'url': 'http://twitter.com/search?q=%23TheWorstMarriagesInclude', 'promoted_content': None, 'query': '%23TheWorstMarriagesInclude', 'tweet_volume': None}, 
                      {'name': '#firstclassmuzic', 'url': 'http://twitter.com/search?q=%23firstclassmuzic', 'promoted_content': None, 'query': '%23firstclassmuzic', 'tweet_volume': None}, 
                      {'name': '#TongueOutTuesday', 'url': 'http://twitter.com/search?q=%23TongueOutTuesday', 'promoted_content': None, 'query': '%23TongueOutTuesday', 'tweet_volume': None}, 
                      {'name': '#oneCCPS', 'url': 'http://twitter.com/search?q=%23oneCCPS', 'promoted_content': None, 'query': '%23oneCCPS', 'tweet_volume': None}, 
                      {'name': '#SweetTalk', 'url': 'http://twitter.com/search?q=%23SweetTalk', 'promoted_content': None, 'query': '%23SweetTalk', 'tweet_volume': None}, 
                      {'name': '#BedbugBret', 'url': 'http://twitter.com/search?q=%23BedbugBret', 'promoted_content': None, 'query': '%23BedbugBret', 'tweet_volume': None}, 
                      {'name': '#FPS19', 'url': 'http://twitter.com/search?q=%23FPS19', 'promoted_content': None, 'query': '%23FPS19', 'tweet_volume': None}, 
                      {'name': '#tangled', 'url': 'http://twitter.com/search?q=%23tangled', 'promoted_content': None, 'query': '%23tangled', 'tweet_volume': None}, 
                      {'name': '#FortniteXMayhem', 'url': 'http://twitter.com/search?q=%23FortniteXMayhem', 'promoted_content': None, 'query': '%23FortniteXMayhem', 'tweet_volume': 17294}, 
                      {'name': '#TestimonialTuesday', 'url': 'http://twitter.com/search?q=%23TestimonialTuesday', 'promoted_content': None, 'query': '%23TestimonialTuesday', 'tweet_volume': None}],
                 'as_of': '2019-08-27T17:41:15Z',
                 'created_at': '2019-08-27T17:36:40Z',
                 'locations': [
                        {'name': 'Baton Rouge', 'woeid': 2359991}]
                 }]